apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-advanced.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-advanced.labels" . | nindent 4 }}
type: Opaque
data:
  APP_PASSWORD: {{ .Values.secret.appPassword | b64enc | quote }}
