replicaCount: 3

image:
  repository: nginx
  tag: "1.25-alpine"
  pullPolicy: IfNotPresent

config:
  appMessage: "Hello CKAD Team da Helm!"

secret:
  appPassword: "password123"

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

probes:
  liveness:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

service:
  port: 80
  targetPort: 80
  type: ClusterIP
