apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-test-xmx
  namespace: jvm-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mem-test-xmx
  template:
    metadata:
      labels:
        app: mem-test-xmx
    spec:
      containers:
        - name: app
          image: memory-eater:latest
          command: ["java"]
          args: ["-Xms128m", "-Xmx256m", "MemoryEater"]
          resources:
            limits:
              memory: "512Mi"