apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-advanced.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-advanced.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "helm-advanced.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
